Fix a bug in subgraph rewriters.
Summary:
Due to not clearing nodes_to_delete_, when we try to write graph rewrite
pass with multiple patterns, this is observed:
IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Test Plan:
The PR stacked on top of this run into this error in the unit test.

Reviewers:

Subscribers:

Tasks:

Tags:

ghstack-source-id: 67cf82c27572a7213ff1dc30e0af2e55d2f3b9fc
Pull Request resolved: https://github.com/pytorch/pytorch/pull/35704